name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        react-version: ['18.*', '19.*']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Install react
        run: npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}

      - name: Lint, format and type check
        run: npm run verify

      - name: Build
        run: npm run build

      - name: Test
        run: npm run coverage

      - name: Send coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
